chumby8: make simple automatic time save daemon
This is done entirely as a shell script. The daemon runs very early in
the boot process. It loads the time from our fake "RTC" in the
cryptoprocessor combined with the file we save in /etc, if the file
exists. If the file doesn't exist, it waits until the date/time gets set
automatically by NTP.

Once a good date/time has been received from NTP, it saves the current
time and the cryptoprocessor's uptime to a file so it can be retrieved
at the next startup.

Note that the automatic save does result in a quick remount of the SD
card. I'm considering moving some of these settings files to a different
settings partition that will be kept read/write at all times.

diff --git a/board/chumby/chumby8/rootfs-overlay/etc/init.d/S00datetime b/board/chumby/chumby8/rootfs-overlay/etc/init.d/S00datetime
--- a/board/chumby/chumby8/rootfs-overlay/etc/init.d/S00datetime
+++ b/board/chumby/chumby8/rootfs-overlay/etc/init.d/S00datetime
@@ -1,28 +1,37 @@
 #!/bin/sh
 
+DAEMON="/scripts/auto_time_save.sh"
+PIDFILE="/var/run/auto_time_save.pid"
+
 start() {
-	echo -n 'Restoring date/time: '
-	if [ -f /etc/coprocessor_uptime ]; then
-		/scripts/restore_datetime.sh
-		status=$?
-		if [ "$status" -eq 0 ]; then
-			echo "OK"
-		else
-			echo "FAIL"
-		fi
-		return "$status"
+	printf "Starting date/time sync: "
+
+	start-stop-daemon -b -m -S -q -p "$PIDFILE" -x "$DAEMON"
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		echo "OK"
 	else
-		echo "SKIPPED"
-		return 0
+		echo "FAIL"
 	fi
+	return "$status"
 }
 
 stop() {
-	return 0
+	printf "Stopping date/time sync: "
+	start-stop-daemon -K -q -p "$PIDFILE"
+	status=$?
+	if [ "$status" -eq 0 ]; then
+		rm -f "$PIDFILE"
+		echo "OK"
+	else
+		echo "FAIL"
+	fi
+	return "$status"
 }
 
 restart() {
 	stop
+	sleep 1
 	start
 }
 
@@ -30,6 +39,7 @@ case "$1" in
 	start|stop|restart)
 		"$1";;
 	reload)
+		# Restart, since there is no true "reload" feature.
 		restart;;
 	*)
 		echo "Usage: $0 {start|stop|restart|reload}"
